In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../../raw_data/cars.csv', index_col='Unnamed: 0')
df

speed  dist
1       4     2
2       4    10
3       7     4
4       7    22
5       8    16
6       9    10
7      10    18
8      10    26
9      10    34
10     11    17
11     11    28
12     12    14
13     12    20
14     12    24
15     12    28
16     13    26
17     13    34
18     13    34
19     13    46
20     14    26
21     14    36
22     14    60
23     14    80
24     15    20
25     15    26
26     15    54
27     16    32
28     16    40
29     17    32
30     17    40
31     17    50
32     18    42
33     18    56
34     18    76
35     18    84
36     19    36
37     19    46
38     19    68
39     20    32
40     20    48
41     20    52
42     20    56
43     20    64
44     22    66
45     23    54
46     24    70
47     24    92
48     24    93
49     24   120
50     25    85

In [4]:
df[['speed']].values.shape

(50, 1)

In [5]:
x= torch.FloatTensor( df[['speed']].values )
y= torch.FloatTensor( df[['dist']].values )

In [6]:
linear = Linear( 1,1 ) # 특성데이터갯수, 라벨의 갯수 w,b 

In [7]:
linear.weight

Parameter containing:
tensor([[0.3592]], requires_grad=True)

In [8]:
linear.bias

Parameter containing:
tensor([0.2024], requires_grad=True)

In [9]:
list( linear.parameters() )

[Parameter containing:
 tensor([[0.3592]], requires_grad=True),
 Parameter containing:
 tensor([0.2024], requires_grad=True)]

In [10]:
model = Sequential()
model.add_module( 'nn1', linear )
loss_fn = MSELoss()
optimizer = Adam( model.parameters(), lr= 0.1 )

In [11]:
for step in range(1000):
#     hx = linear.forward(x) # w*x + b
    hx = model.forward(x)
    # hx = linear(x)  #linear.forward(x)
    optimizer.zero_grad()
    c = loss_fn( hx, y )
    c.backward()
    optimizer.step()
    print( 'cost', c.item() )

cost 1964.1622314453125
cost 1825.378173828125
cost 1692.6956787109375
cost 1566.2119140625
cost 1446.009033203125
cost 1332.1522216796875
cost 1224.6881103515625
cost 1123.6427001953125
cost 1029.0203857421875
cost 940.8027954101562
cost 858.9466552734375
cost 783.3828125
cost 714.0159912109375
cost 650.723388671875
cost 593.3543701171875
cost 541.7310180664062
cost 495.6480407714844
cost 454.8736572265625
cost 419.1512145996094
cost 388.2010192871094
cost 361.7222595214844
cost 339.3968505859375
cost 320.8920593261719
cost 305.86456298828125
cost 293.9648132324219
cost 284.84124755859375
cost 278.14532470703125
cost 273.5354309082031
cost 270.6820068359375
cost 269.2714538574219
cost 269.0098876953125
cost 269.6264953613281
cost 270.87591552734375
cost 272.5405578613281
cost 274.43133544921875
cost 276.3883972167969
cost 278.2807312011719
cost 280.005126953125
cost 281.4848327636719
cost 282.6673889160156
cost 283.52215576171875
cost 284.0377197265625
cost 284.2190856933594
cost 284.

In [12]:
linear.weight

Parameter containing:
tensor([[3.7907]], requires_grad=True)

In [13]:
linear.bias

Parameter containing:
tensor([-15.1609], requires_grad=True)

In [14]:
linear.forward( torch.FloatTensor( [[5],[7]] ) )

tensor([[ 3.7928],
        [11.3743]], grad_fn=<AddmmBackward0>)

In [15]:
linear(  torch.FloatTensor( [[5],[7]] )  )

tensor([[ 3.7928],
        [11.3743]], grad_fn=<AddmmBackward0>)