In [7]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv( '../../raw_data/test.csv', header=None)
df.columns = ['q1','q2','mid','final']
df

q1  q2  mid  final
0   73  80   75    152
1   93  88   93    185
2   89  91   90    180
3   96  98  100    196
4   73  66   70    142
5   53  46   55    101
6   69  74   77    149
7   47  56   60    115
8   87  79   90    175
9   79  70   88    164
10  69  70   73    141
11  70  65   74    141
12  93  95   91    184
13  79  80   73    152
14  70  73   78    148
15  93  89   96    192
16  78  75   68    147
17  81  90   93    183
18  88  92   86    177
19  78  83   77    159
20  82  86   90    177
21  86  82   89    175
22  78  83   85    175
23  76  83   71    149
24  96  93   95    192

In [9]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1] ].values

In [10]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [11]:
model = Sequential()
model.add_module( 'nn1', Linear(3,1) ) # w: 3x1, b:1
loss_fn = MSELoss()
optimizer = Adam( model.parameters(), lr=0.1 )

In [17]:
for epoch in range(1000):
    optimizer.zero_grad()
    hx = model.forward( x ) # matmul( x,w) +b 
    # hx = model(x)
    c = loss_fn( hx, y) 
    c.backward()
    optimizer.step()
    print( epoch, c.item() )

0 6.307157516479492
1 6.306331157684326
2 6.305498123168945
3 6.304688930511475
4 6.30388069152832
5 6.303056716918945
6 6.302252292633057
7 6.30143928527832
8 6.300625801086426
9 6.299808979034424
10 6.299006462097168
11 6.298211574554443
12 6.29741096496582
13 6.296621322631836
14 6.295816421508789
15 6.295020580291748
16 6.294226169586182
17 6.293441295623779
18 6.292654991149902
19 6.291865348815918
20 6.291089057922363
21 6.290297031402588
22 6.289519786834717
23 6.2887396812438965
24 6.2879719734191895
25 6.287200450897217
26 6.2864203453063965
27 6.2856526374816895
28 6.284888744354248
29 6.284121513366699
30 6.283365249633789
31 6.2826008796691895
32 6.281826019287109
33 6.281075477600098
34 6.280314922332764
35 6.279564380645752
36 6.278811454772949
37 6.278074741363525
38 6.277308940887451
39 6.276557445526123
40 6.275812149047852
41 6.2750749588012695
42 6.274334907531738
43 6.273586273193359
44 6.2728590965271
45 6.272121429443359
46 6.271385669708252
47 6.270651340484619
4

In [13]:
model[0].weight #결과는

Parameter containing:
tensor([[0.4434, 0.5227, 1.0491]], requires_grad=True)

In [14]:
model( torch.FloatTensor( [[90,90,100]] ) )

tensor([[191.9003]], grad_fn=<AddmmBackward0>)

In [15]:
model( torch.FloatTensor( [[50,60,70], [90,90,100] ] ) ).detach().numpy()

array([[127.00943],
       [191.90025]], dtype=float32)