In [2]:
import torch
torch.__version__

'1.13.0'

In [10]:
aa = torch.tensor(100)
aa

tensor(100)

In [11]:
# for scalar
aa.item()

100

In [28]:
bb = torch.tensor([10,20,30,40])
bb

tensor([10, 20, 30, 40])

In [29]:
bb.dtype

torch.int64

In [30]:
# for verctor and tensor
bb.numpy()

array([10, 20, 30, 40])

In [31]:
cc = torch.IntTensor([10,20,30,40])
cc

tensor([10, 20, 30, 40], dtype=torch.int32)

In [32]:
cc.dtype

torch.int32

In [33]:
dd = torch.LongTensor([10,20,30,40])
dd

tensor([10, 20, 30, 40])

In [34]:
dd.dtype

torch.int64

In [51]:
a = torch.tensor(3)
b = torch.tensor([10,20,30],dtype=torch.float32)
c = torch.multiply(a,b)

In [52]:
c

tensor([30., 60., 90.])

In [53]:
b.mean()

tensor(20.)

In [54]:
torch.mean(b)

tensor(20.)