In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam

x_data = np.array([[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]])
y_data = np.array([[0],[0],[0],[1],[1],[1]])

In [9]:
# xavier, he(최적의 초기화 알고리즘)
x = tf.constant(x_data,tf.float32)
y = tf.constant(y_data,tf.float32)

initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[2,1]))
b = tf.Variable(initX(shape=[1]))


In [10]:
def cost():
    z = tf.matmul(x,w) + b
    c_i = tf.nn.sigmoid_cross_entropy_with_logits(labels=y,logits=z)
    c = tf.reduce_mean(c_i)
    return c

In [11]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(cost,var_list=[w,b])
    print(i,'cost:',cost().numpy())

0 cost: 0.8683729
1 cost: 0.7194065
2 cost: 0.637899
3 cost: 0.6419636
4 cost: 0.68364924
5 cost: 0.69614977
6 cost: 0.66782373
7 cost: 0.61774623
8 cost: 0.5681576
9 cost: 0.5331875
10 cost: 0.51551574
11 cost: 0.50921226
12 cost: 0.5059092
13 cost: 0.49937397
14 cost: 0.4868146
15 cost: 0.4683425
16 cost: 0.4460028
17 cost: 0.4228636
18 cost: 0.40214014
19 cost: 0.38624236
20 cost: 0.3758244
21 cost: 0.3693186
22 cost: 0.3636013
23 cost: 0.3557405
24 cost: 0.34464484
25 cost: 0.33136916
26 cost: 0.31806272
27 cost: 0.3065583
28 cost: 0.2975548
29 cost: 0.29064077
30 cost: 0.2848226
31 cost: 0.27909732
32 cost: 0.2728173
33 cost: 0.26580676
34 cost: 0.2582965
35 cost: 0.25075397
36 cost: 0.24367678
37 cost: 0.2374047
38 cost: 0.23200259
39 cost: 0.2272558
40 cost: 0.22278544
41 cost: 0.21823025
42 cost: 0.21340422
43 cost: 0.2083461
44 cost: 0.20325267
45 cost: 0.1983515
46 cost: 0.19379286
47 cost: 0.1896056
48 cost: 0.18571655
49 cost: 0.18200462
50 cost: 0.17835662
51 cost: 0.17470

In [23]:
def hxFn(xdata):
    xd = tf.constant(xdata,tf.float32)
    z = tf.matmul(xd,w) + b
    hx = tf.nn.sigmoid(z)
    return (hx.numpy()>0.5) + 0

In [24]:
hxFn([[5,5]])

array([[1]])

In [25]:
hxFn([[1,1]])

array([[0]])

In [26]:
pred = hxFn(x_data)

In [27]:
pred

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [28]:
y_data

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [30]:
(pred == y_data).mean()

1.0

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(pred,y_data)

1.0