In [17]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam



x_data = np.array([[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]])
y_data = np.array([[0],[0],[0],[1],[1],[1]])

In [25]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='acc',patience=200)

model = Sequential()
dense = Dense(units=1,input_dim=2, activation='sigmoid')
model.add(dense)
model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=1e-1), metrics=['acc'])
hist = model.fit(x_data, y_data, epochs=1000, verbose=1,
                 callbacks=[es]
                 )

Epoch 1/1000
1/1 [==============================] - 0s 194ms/step - loss: 0.8307 - acc: 0.3333
Epoch 2/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6715 - acc: 0.6667
Epoch 3/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6483 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6638 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6678 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6507 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6193 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.5843 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.5561 - acc: 0.6667
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.5409 - acc: 0.6667
Epoch 11/1000
1/1 [==============================] - 0s 7ms/step - 

2022-12-01 11:20:53.741276: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 6ms/step - loss: 0.5226 - acc: 0.8333
Epoch 14/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.5033 - acc: 0.8333
Epoch 15/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.4808 - acc: 0.8333
Epoch 16/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.4611 - acc: 0.8333
Epoch 17/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.4468 - acc: 0.8333
Epoch 18/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.4370 - acc: 0.8333
Epoch 19/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.4287 - acc: 0.6667
Epoch 20/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.4194 - acc: 0.6667
Epoch 21/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.4080 - acc: 0.8333
Epoch 22/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.3946 - acc: 0.8333
Epoch 23/1000
1/1 [==============================] - 0s 7ms/step - loss: 0

In [19]:
w,b = dense.get_weights()
print(w,b)

[[1.1795399]
 [1.1711287]] [-7.801134]


In [20]:
model.predict([[5,6]])

1/1 [==============================] - 0s 61ms/step


2022-12-01 11:17:36.503276: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


array([[0.99407923]], dtype=float32)

In [22]:
(model.predict(x_data) > 0.5) + 0

1/1 [==============================] - 0s 14ms/step


array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])