In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [2]:
df = pd.read_csv('./raw_data/softmax.txt',sep=' ',header=None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [3]:
x_data = df.iloc[:,:-3]
y_data = df.iloc[:,-3:]

In [4]:
print(x_data.shape)
print(y_data.shape)

(8, 2)
(8, 3)


In [8]:
dense = Dense(units=3,input_dim=2,activation='sigmoid')
model = Sequential([dense])
model.compile(
    loss='categorical_crossentropy',
    optimizer=Adam(learning_rate=0.1),
    metrics=['acc']
)
h= model.fit(x_data,y_data,epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 221ms/step - loss: 4.4059 - acc: 0.2500
Epoch 2/200
1/1 [==============================] - 0s 7ms/step - loss: 3.1969 - acc: 0.2500
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 2.0817 - acc: 0.2500
Epoch 4/200
1/1 [==============================] - 0s 8ms/step - loss: 1.2766 - acc: 0.3750
Epoch 5/200
1/1 [==============================] - 0s 8ms/step - loss: 1.1837 - acc: 0.3750
Epoch 6/200
1/1 [==============================] - 0s 9ms/step - loss: 1.3777 - acc: 0.3750
Epoch 7/200
1/1 [==============================] - 0s 9ms/step - loss: 1.5173 - acc: 0.5000
Epoch 8/200
1/1 [==============================] - 0s 8ms/step - loss: 1.6786 - acc: 0.3750
Epoch 9/200
1/1 [==============================] - 0s 8ms/step - loss: 1.7691 - acc: 0.5000
Epoch 10/200
1/1 [==============================] - 0s 9ms/step - loss: 1.7058 - acc: 0.5000
Epoch 11/200
1/1 [==============================] - 0s 8ms/step - loss: 1.533

2022-12-02 11:09:18.809513: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 8ms/step - loss: 0.9571 - acc: 0.5000
Epoch 17/200
1/1 [==============================] - 0s 8ms/step - loss: 1.0646 - acc: 0.5000
Epoch 18/200
1/1 [==============================] - 0s 9ms/step - loss: 1.1446 - acc: 0.5000
Epoch 19/200
1/1 [==============================] - 0s 12ms/step - loss: 1.1553 - acc: 0.5000
Epoch 20/200
1/1 [==============================] - 0s 8ms/step - loss: 1.0990 - acc: 0.5000
Epoch 21/200
1/1 [==============================] - 0s 8ms/step - loss: 1.0069 - acc: 0.5000
Epoch 22/200
1/1 [==============================] - 0s 8ms/step - loss: 0.9234 - acc: 0.5000
Epoch 23/200
1/1 [==============================] - 0s 8ms/step - loss: 0.8811 - acc: 0.5000
Epoch 24/200
1/1 [==============================] - 0s 8ms/step - loss: 0.8744 - acc: 0.6250
Epoch 25/200
1/1 [==============================] - 0s 8ms/step - loss: 0.8752 - acc: 0.6250
Epoch 26/200
1/1 [==============================] - 0s 8ms/step - loss: 0.8695 - a

In [9]:
w,b = dense.get_weights()

In [10]:
w

array([[-0.20840554, -0.37438178, -0.5734316 ],
       [ 1.1393682 ,  0.3785569 , -0.8996375 ]], dtype=float32)

In [11]:
b

array([-4.8372645 ,  0.53998965,  6.3595333 ], dtype=float32)

In [13]:
model.predict([[1,1],[5,6]]).argmax(axis=1)

1/1 [==============================] - 0s 24ms/step


array([2, 0])

In [14]:
model.evaluate(x_data,y_data)

1/1 [==============================] - 0s 85ms/step - loss: 0.4169 - acc: 1.0000


2022-12-02 11:11:26.282018: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


[0.4168723225593567, 1.0]