In [32]:
import torch
import torch.nn.functional as F

"""for batch train"""
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import pandas as pd

In [37]:
class Mydata(Dataset):
    """
    For torch, 
    Batch Train
    """
    def __init__(self) -> None:
        super().__init__()
        self.x_data = [
            [10,20],
            [30,40],
            [33,43],
            [50,60],
            [70,80],
            [90,92]
            ]
        self.y_data = [
            [100],
            [110],
            [115],
            [130],
            [135],
            [140],
            ]
    
    def __len__(self):
        """
        data length
        """
        return len(self.x_data)
    
    def __getitem__(self, index):
        """
        data => torch.FloatTensor
        """
        x = torch.FloatTensor(self.x_data[index])
        y = torch.FloatTensor(self.y_data[index])
        return x,y

In [47]:
dataset = Mydata()
dataloader = DataLoader(dataset, batch_size=3, shuffle=True)

In [48]:
model = torch.nn.Linear(in_features=2, out_features=1)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
for epoch in range(10):
    for batch_idx, samples in enumerate(dataloader):
        print(f'batch_idx : {batch_idx}')
        print(f'samples : \n{samples[0]} \n {samples[1]}')
        print('='*10)
        x_train, y_train = samples
        
        hx = model.forward(x_train)
        cost = F.mse_loss(hx,y_train)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        print(f'epoch => {epoch} / cost : {cost.item()} / \
            MSE : {mean_squared_error(hx.detach().numpy(),y_train.detach().numpy())}')
        # print(f'epoch => {epoch} / cost : {cost.item()}')
    print('='*100)

batch_idx : 0
samples : 
tensor([[50., 60.],
        [90., 92.],
        [33., 43.]]) 
 tensor([[130.],
        [140.],
        [115.]])
epoch => 0 / cost : 37700.81640625 /             MSE : 37700.81640625
batch_idx : 1
samples : 
tensor([[70., 80.],
        [30., 40.],
        [10., 20.]]) 
 tensor([[135.],
        [110.],
        [100.]])
epoch => 0 / cost : 26377.927734375 /             MSE : 26377.927734375
batch_idx : 0
samples : 
tensor([[90., 92.],
        [70., 80.],
        [30., 40.]]) 
 tensor([[140.],
        [135.],
        [110.]])
epoch => 1 / cost : 39152.06640625 /             MSE : 39152.06640625
batch_idx : 1
samples : 
tensor([[50., 60.],
        [33., 43.],
        [10., 20.]]) 
 tensor([[130.],
        [115.],
        [100.]])
epoch => 1 / cost : 23425.2578125 /             MSE : 23425.2578125
batch_idx : 0
samples : 
tensor([[10., 20.],
        [30., 40.],
        [70., 80.]]) 
 tensor([[100.],
        [110.],
        [135.]])
epoch => 2 / cost : 25510.568359375

In [24]:
hx.detach().numpy()

array([[-7.709188],
       [-6.142795]], dtype=float32)

In [31]:
y_train

tensor([[50., 60.],
        [30., 40.]])