In [2]:
import tensorflow as tf
from tensorflow.keras.optimizers import Adam, SGD
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, StandardScaler

다중(특성데이터가 여러개)
1. 상관관계(corr):낮은것 컬럼제거
2. 다중공선성확인( statsmodel): 높은컬럼한개만 선택
3. 정규화(무조건)

In [3]:
data = [[828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

In [4]:
df = pd.DataFrame(data)
df

0      1          2       3       4
0  828.0  920.0  1234567.0  1020.0  1111.0
1  824.0  910.0  2345612.0  1090.0  1234.0
2  880.0  900.0  3456123.0  1010.0  1000.0
3  870.0  990.0  2312123.0  1001.0  1122.0
4  860.0  980.0  3223123.0  1008.0  1133.0
5  850.0  970.0  2432123.0  1100.0  1221.0

In [5]:
x_data = df.iloc[:,:-1]
y_data = df.iloc[:, [-1] ]

In [6]:
scaleF = MinMaxScaler()
x_dataN = scaleF.fit_transform( x_data)

In [7]:
scaleL = MinMaxScaler()
y_dataN = scaleL.fit_transform( y_data)

In [8]:
x_dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933],
       [0.        , 0.11111164, 0.50012016, 0.89899063],
       [1.        , 0.        , 1.        , 0.09090996],
       [0.8214283 , 1.        , 0.48504567, 0.        ],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        ]], dtype=float32)

In [9]:
y_dataN

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [10]:
x = tf.constant( x_dataN, tf.float32)
y = tf.constant( y_dataN, tf.float32)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-11-30 20:40:07.243719: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-11-30 20:40:07.244334: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [11]:
w = tf.Variable( tf.random.uniform([4,1]) )#[특성데이터갯수, 라벨의갯수]
b = tf.Variable( tf.random.uniform([1]) ) # 라벨의 갯수

In [12]:
def cost():
    hx = tf.matmul( x, w ) + b
    c = tf.reduce_mean( (hx-y)**2)
    return c

In [13]:
optimizer = Adam( learning_rate=0.1 )
hist_cost=[]
for i in range( 1000):
    optimizer.minimize( cost, var_list=[w,b] )
    c = cost().numpy()
    hist_cost.append( c )
    print( i, 'cost=', c )

0 cost= 0.19511192
1 cost= 0.11538488
2 cost= 0.11230274
3 cost= 0.11412596
4 cost= 0.09145054
5 cost= 0.056149326
6 cost= 0.028568134
7 cost= 0.02077684
8 cost= 0.030568361
9 cost= 0.044790983
10 cost= 0.050990492
11 cost= 0.04631736
12 cost= 0.036315277
13 cost= 0.02850483
14 cost= 0.026876118
15 cost= 0.029906914
16 cost= 0.0326704
17 cost= 0.031136682
18 cost= 0.025022132
19 cost= 0.017338995
20 cost= 0.0118114455
21 cost= 0.010305755
22 cost= 0.011858742
23 cost= 0.013791777
24 cost= 0.013933517
25 cost= 0.012111156
26 cost= 0.009864792
27 cost= 0.008921472
28 cost= 0.009773322
29 cost= 0.011407933
30 cost= 0.012268613
31 cost= 0.011540154
32 cost= 0.009675667
33 cost= 0.007852597
34 cost= 0.0069530844
35 cost= 0.006940241
36 cost= 0.0070740967
37 cost= 0.006677886
38 cost= 0.005730325
39 cost= 0.004798279
40 cost= 0.0044610407
41 cost= 0.0047932337
42 cost= 0.0053509395
43 cost= 0.005613503
44 cost= 0.0054299897
45 cost= 0.005069336
46 cost= 0.004888721
47 cost= 0.00498001
48 cos

In [14]:
def hxFn( xdata ):
    xd = tf.constant( xdata, tf.float32)
    hx = tf.matmul( xd, w ) + b
    return hx.numpy()

In [15]:
xn = scaleF.transform( [[828, 920, 1234567, 1020]] )

In [16]:
pred = hxFn( xn )

In [17]:
scaleL.inverse_transform( pred )

array([[1122.8623]], dtype=float32)