In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import numpy as np

In [2]:
x_data = np.array([[1,1],[1,0],[0,1],[0,0]])
y_data = np.array([[0],[1],[1],[0]])

In [4]:
model_logistic = LogisticRegression(max_iter=100,verbose=1)
model_logistic.fit(x_data,y_data.reshape(-1))

RUNNING THE L-BFGS-B CODE

           * * *



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
 This problem is unconstrained.


LogisticRegression(verbose=1)

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.77259D+00    |proj g|=  0.00000D+00

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    3      0      1      0     0     0   0.000D+00   2.773D+00
  F =   2.7725887222397811     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            


In [5]:
model_logistic.predict(x_data)

array([0, 0, 0, 0])

In [6]:
model_logistic.score(x_data,y_data)

0.5

In [15]:
print(model_logistic.coef_)
print(model_logistic.intercept_)

[[0. 0.]]
[0.]


In [10]:
"""
Multi - Layer - Perceptron - Classifier
"""
model_mlp = MLPClassifier(verbose=1,
                          hidden_layer_sizes=(100,), # default
                          learning_rate='adaptive',
                          max_iter=1000)
model_mlp.fit(x_data,y_data.reshape(-1))

Iteration 1, loss = 0.70110451
Iteration 2, loss = 0.69887399
Iteration 3, loss = 0.69672721
Iteration 4, loss = 0.69465599
Iteration 5, loss = 0.69265965
Iteration 6, loss = 0.69070528
Iteration 7, loss = 0.68882461
Iteration 8, loss = 0.68695600
Iteration 9, loss = 0.68510926
Iteration 10, loss = 0.68330243
Iteration 11, loss = 0.68153372
Iteration 12, loss = 0.67980694
Iteration 13, loss = 0.67811733
Iteration 14, loss = 0.67645464
Iteration 15, loss = 0.67481382
Iteration 16, loss = 0.67319378
Iteration 17, loss = 0.67157945
Iteration 18, loss = 0.66997391
Iteration 19, loss = 0.66838067
Iteration 20, loss = 0.66678803
Iteration 21, loss = 0.66522787
Iteration 22, loss = 0.66369249
Iteration 23, loss = 0.66215380
Iteration 24, loss = 0.66057594
Iteration 25, loss = 0.65898269
Iteration 26, loss = 0.65739526
Iteration 27, loss = 0.65584355
Iteration 28, loss = 0.65430644
Iteration 29, loss = 0.65280403
Iteration 30, loss = 0.65130707
Iteration 31, loss = 0.64980479
Iteration 32, los

MLPClassifier(learning_rate='adaptive', max_iter=1000, verbose=1)

In [11]:
model_mlp.predict(x_data)

array([0, 1, 1, 0])

In [12]:
model_mlp.score(x_data,y_data)

1.0

In [14]:
model_mlp.get_params()

{'activation': 'relu',
 'alpha': 0.0001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'adaptive',
 'learning_rate_init': 0.001,
 'max_fun': 15000,
 'max_iter': 1000,
 'momentum': 0.9,
 'n_iter_no_change': 10,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 1,
 'warm_start': False}

In [27]:
print(len(model_mlp.coefs_))
print(len(model_mlp.intercepts_))

2
2


In [25]:
print(model_mlp.coefs_[0].shape)
print(model_mlp.intercepts_[0].shape)

(2, 100)
(100,)


In [26]:
print(model_mlp.coefs_[1].shape)
print(model_mlp.intercepts_[1].shape)

(100, 1)
(1,)


In [ ]:
model_mlp = MLPClassifier(verbose=0,
                          hidden_layer_sizes=(100,50),
                          learning_rate='adaptive',
                          max_iter=30)
model_mlp.fit(x_data,y_data.reshape(-1))

print(len(model_mlp.coefs_))
print(len(model_mlp.intercepts_))
print(model_mlp.coefs_[0].shape)
print(model_mlp.intercepts_[0].shape)
print(model_mlp.coefs_[1].shape)
print(model_mlp.intercepts_[1].shape)
print(model_mlp.coefs_[2].shape)
print(model_mlp.intercepts_[2].shape)
print(model_mlp.coefs_[3].shape)
print(model_mlp.intercepts_[3].shape)

In [38]:
model_mlp = MLPClassifier(verbose=0,
                          hidden_layer_sizes=(100,50,30),
                          learning_rate='adaptive',
                          max_iter=30)
model_mlp.fit(x_data,y_data.reshape(-1))

print(len(model_mlp.coefs_))
print(len(model_mlp.intercepts_))
print(model_mlp.coefs_[0].shape)
print(model_mlp.intercepts_[0].shape)
print(model_mlp.coefs_[1].shape)
print(model_mlp.intercepts_[1].shape)
print(model_mlp.coefs_[2].shape)
print(model_mlp.intercepts_[2].shape)
print(model_mlp.coefs_[3].shape)
print(model_mlp.intercepts_[3].shape)

4
4
(2, 100)
(100,)
(100, 50)
(50,)
(50, 30)
(30,)
(30, 1)
(1,)


/opt/homebrew/Caskroom/miniforge/base/envs/deep_learning/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (30) reached and the optimization hasn't converged yet.
  warnings.warn(
