In [1]:
import numpy as np
import math

In [2]:
def fn(x):
    print(x/x.sum())

In [3]:
arr = np.array([2.,1.,.1])
fn(arr)

[0.64516129 0.32258065 0.03225806]


In [4]:
def softmax(x):
    e = np.exp(x)
    print(e)
    print('='*10)
    print(e/e.sum())

In [6]:
arr = np.array([2.,1.,.1])
softmax(arr)

[7.3890561  2.71828183 1.10517092]
[0.65900114 0.24243297 0.09856589]
